"""Dockerfile generation for paude."""

from __future__ import annotations

from typing import TYPE_CHECKING

from paude.config.models import PaudeConfig
from paude.constants import CONTAINER_ENTRYPOINT, CONTAINER_HOME

if TYPE_CHECKING:
    from paude.agents.base import Agent


def generate_pip_install_dockerfile(
    config: PaudeConfig,
    include_claude_install: bool = False,
    agent: Agent | None = None,
) -> str:
    """Generate a minimal Dockerfile that layers on a paude base image.

    Use this when layering on top of the default paude image which already has
    entrypoints and all system packages installed.

    Args:
        config: Parsed paude configuration.
        include_claude_install: If True, include Claude Code installation.
            Used for OpenShift remote builds where the base image doesn't have Claude.

    Returns:
        Generated Dockerfile content.
    """
    lines: list[str] = []

    lines.append("# Auto-generated by paude - DO NOT EDIT")
    lines.append("ARG BASE_IMAGE")
    lines.append("FROM ${BASE_IMAGE}")

    if include_claude_install:
        if agent is None:
            from paude.agents import get_agent

            agent = get_agent("claude")

        # Switch to root first in case base image ends with non-root user
        # This ensures any feature injection (done before USER paude) runs as root
        lines.append("")
        lines.append("# Ensure root for any feature installation")
        lines.append("USER root")

        lines.extend(agent.dockerfile_install_lines(CONTAINER_HOME))

        lines.append("")
        lines.append("# Switch back to paude user for runtime")
        lines.append("USER paude")
        lines.append(f"WORKDIR {CONTAINER_HOME}")

    if not include_claude_install:
        # Add minimal structure for feature injection compatibility.
        # Features are injected before the first USER paude line.
        lines.append("")
        lines.append("# Ensure root for any feature installation")
        lines.append("USER root")
        lines.append("")
        lines.append("USER paude")
        lines.append(f"WORKDIR {CONTAINER_HOME}")

    return "\n".join(lines)


def generate_workspace_dockerfile(
    config: PaudeConfig,
    agent: Agent | None = None,
) -> str:
    """Generate a Dockerfile that wraps the user's base image with paude requirements.

    This output matches the bash generate_workspace_dockerfile() function exactly.

    Args:
        config: Parsed paude configuration.

    Returns:
        Generated Dockerfile content.
    """
    lines: list[str] = []

    # Header
    lines.append("# Auto-generated by paude - DO NOT EDIT")
    lines.append("ARG BASE_IMAGE")
    lines.append("FROM ${BASE_IMAGE}")

    # Ensure we're running as root for package installation
    # (important for multi-stage builds where stage 1 may end with non-root user)
    lines.append("")
    lines.append("USER root")

    # Add user-specified packages if any (from paude.json "packages" array)
    if config.packages:
        pkg_list = " ".join(config.packages)
        lines.append("")
        lines.append("# User-specified packages from paude.json")
        lines.append(f"""RUN if command -v apt-get >/dev/null 2>&1; then \\
        apt-get update && apt-get install -y {pkg_list} && rm -rf /var/lib/apt/lists/*; \\
    elif command -v apk >/dev/null 2>&1; then \\
        apk add --no-cache {pkg_list}; \\
    elif command -v dnf >/dev/null 2>&1; then \\
        dnf install -y {pkg_list} && dnf clean all; \\
    elif command -v yum >/dev/null 2>&1; then \\
        yum install -y {pkg_list} && yum clean all; \\
    fi""")

    # Standard paude requirements (including tmux for OpenShift session persistence)
    lines.append("")
    lines.append("""# Install required system packages
RUN if command -v apt-get >/dev/null 2>&1; then \\
        apt-get update && \\
        apt-get install -y --no-install-recommends \\
            git curl ca-certificates bash tmux locales \\
            coreutils findutils grep sed gawk diffutils less file \\
            tar gzip xz-utils unzip zip && \\
        rm -rf /var/lib/apt/lists/* && \\
        localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8; \\
    elif command -v apk >/dev/null 2>&1; then \\
        apk add --no-cache git curl ca-certificates bash tmux \\
            coreutils findutils grep sed gawk diffutils less file \\
            tar gzip xz unzip zip; \\
    elif command -v dnf >/dev/null 2>&1; then \\
        dnf install -y --allowerasing \\
            git curl ca-certificates bash tmux glibc-langpack-en \\
            which coreutils findutils grep sed gawk diffutils less file \\
            tar gzip xz unzip zip && \\
        dnf clean all; \\
    elif command -v yum >/dev/null 2>&1; then \\
        yum install -y --allowerasing \\
            git curl ca-certificates bash tmux glibc-langpack-en \\
            which coreutils findutils grep sed gawk diffutils less file \\
            tar gzip xz unzip zip && \\
        yum clean all; \\
    else \\
        echo "Warning: Unknown package manager, git may not be available" >&2; \\
    fi""")

    lines.append("")
    lines.append("# Set UTF-8 locale for proper terminal rendering")
    lines.append("ENV LANG=en_US.UTF-8")
    lines.append("ENV LC_ALL=en_US.UTF-8")

    lines.append("")
    lines.append(
        "# Create paude user with root group (GID 0) for OpenShift compatibility"
    )
    lines.append(
        "# OpenShift runs containers with arbitrary UIDs but GID 0, so home must be group-writable"
    )
    if agent is None:
        from paude.agents import get_agent

        agent = get_agent("claude")

    config_dir = agent.config.config_dir_name
    lines.append(
        "RUN (id paude >/dev/null 2>&1 || useradd -m -s /bin/bash -g 0 paude 2>/dev/null || adduser -D -s /bin/bash -G root paude) && "
        f"chmod -R g+rwX {CONTAINER_HOME} && "
        f"mkdir -p {CONTAINER_HOME}/{config_dir} {CONTAINER_HOME}/.config && "
        f"chmod -R g+rwX {CONTAINER_HOME}/{config_dir} {CONTAINER_HOME}/.config"
    )

    lines.extend(agent.dockerfile_install_lines(CONTAINER_HOME))

    lines.append("")
    lines.append("# Copy entrypoints (requires root)")
    lines.append("USER root")
    lines.append(f"COPY entrypoint.sh {CONTAINER_ENTRYPOINT}")
    lines.append("COPY entrypoint-session.sh /usr/local/bin/entrypoint-session.sh")
    lines.append(
        f"RUN chmod +x {CONTAINER_ENTRYPOINT} /usr/local/bin/entrypoint-session.sh"
    )

    lines.append("")
    lines.append("# Fix permissions on directories created by Claude install")
    lines.append(
        "# Must be done as root after Claude install, for OpenShift arbitrary UID"
    )
    lines.append(f"RUN chmod -R g+rwX {CONTAINER_HOME}")

    lines.append("")
    lines.append("USER paude")
    lines.append(f"WORKDIR {CONTAINER_HOME}")
    lines.append(f'ENTRYPOINT ["{CONTAINER_ENTRYPOINT}"]')

    return "\n".join(lines)
